<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var array $query
 * @var bool $pagination
 * @var array $sortHeadings
 * @var array $components
 * @var string $linkText
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$fallbackSetting = $plugins->get('fallbackSetting');

$showThumbnail = in_array('thumbnail', $components);
$showHeading = in_array('resource-heading', $components);
$showBody = in_array('resource-body', $components);
$showThumbnailOrHeading = $showThumbnail || $showHeading;

$headingTerm = $siteSetting('browse_heading_property_term');
$bodyTerm = $siteSetting('browse_body_property_term');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
$langValue = $filterLocale ? [$lang, ''] : null;

$untitled = $translate('[Untitled]');
$siteSlug = $site->slug();

// $totalCount = $this->pagination()->getPaginator()->getTotalCount();
?>

<?php // This block uses two div by default to comply with common themes. ?>

<div class="comments-browse-block">
    <?php if (!empty($sortHeadings)): ?>
    <div class="browse-controls">
        <?= $this->sortSelector($sortHeadings) ?>
    </div>
    <?php endif; ?>

    <ul class="resource-list preview">
    <?php

    $argsComment = [
        'site' => $site,
        'comment' => null,
        'resource' => null,
        'comments' => [],
        'label' => $label ?? (string) $fallbackSetting('comment_label', ['site', 'global']),
        // A single comment is always flat.
        'structure' => 'flat',
        'closedOnLoad' => false,
        'maxLength' => $maxLength ?? (int) $fallbackSetting('comment_max_length', ['site', 'global'], 2000),
        'skipGravatar' => $skipGravatar ?? (bool) $fallbackSetting('comment_skip_gravatar', ['site', 'global'], false),
        'legalText' => $legalText ?? (string) $fallbackSetting('comment_legal_text', ['site', 'global']),
        'parentId' => null,
    ];

    $heading = '';
    $body = '';
    foreach ($comments as $comment):
        $resource = $comment->resource();
        $resourceType = $resource->getControllerName();
        if ($showThumbnailOrHeading) {
            $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $untitled, 'lang' => $langValue]) : null;
            $heading = $heading ? $heading->asHtml() : $escape($resource->displayTitle($untitled, $lang));
        }
        if ($showBody) {
            $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $langValue]) : null;
            $body = $body ? $body->asHtml() : $escape($resource->displayDescription(null, $lang));
        }
        $argsComment['comment'] = $comment;
        $argsComment['resource'] = $resource;
        $argsComment['comments'] = [$comment];
        ?>
        <li class="<?= $resourceType ?> resource">
            <?php // Standard browse preview resource. ?>
            <?php if ($showThumbnail): ?>
            <?= $resource->linkRaw($thumbnail($resource, 'medium', ['title' => $heading])) ?>
            <?php endif; ?>
            <?php if ($showHeading && $heading): ?>
            <h4><span class="resource-name"><?= $resource->linkRaw($heading, null, ['class' => 'resource-link']) ?></span></h4>
            <?php endif; ?>
            <?php if ($showBody && $body): ?>
            <div class="description"><?= $body ?></div>
            <?php endif; ?>
            <?php // Comment on the resource. ?>
            <div id="comment-<?= $comment->id() ?>" class="comment" data-comment-id="<?= $comment->id() ?>">
                <?= $partial('common/comment-single', $argsComment) ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>

    <?php if (!empty($pagination)): ?>
        <?= $this->pagination() ?>
    <?php endif; ?>

    <?php if ($linkText): ?>
        <?= $hyperlink($linkText, $url('site/resource', ['controller' => $resourceType, 'action' => 'browse', 'site-slug' => $siteSlug], ['query' => $query], true)) ?>
    <?php endif; ?>

</div>
